apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: adeku/auth-service
          ports:
            - containerPort: 3000``
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth-service
  type: LoadBalancer
  ports:
    - name: auth-srv
      protocol: TCP
      port: 3000
      targetPort: 3000
