apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-depl
  labels:
    type: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
        - name: myql
          image: mysql:8
          envFrom:
            - secretRef:
                name: db-secret
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: db-srv
spec:
  selector:
    app: db-service
  type: ClusterIP
  ports:
    - name: db-port
      protocol: TCP
      port: 3306
      targetPort: 3306
